# .github/workflows/check-factorio-version.yml
name: Check Factorio Version

on:
  schedule:
    - cron: '0 * * * *'  # 每小时运行一次
  workflow_dispatch:      # 允许手动触发

jobs:
  check-version:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: |
        npm install axios qiniu

    - name: Run version checker
      env:
        QINIU_ACCESS_KEY: ${{ secrets.QINIU_ACCESS_KEY }}
        QINIU_SECRET_KEY: ${{ secrets.QINIU_SECRET_KEY }}
        QINIU_BUCKET: ${{ secrets.QINIU_BUCKET }}
        QINIU_DOMAIN: ${{ secrets.QINIU_DOMAIN }}
      run: node check-factorio-version.js
